export const PLAN_FEATURES = {
  starter: {
    label: "Starter",
    maxLeads: 100,
    canImportCsv: false,
    canUseAiSearch: true,
    aiSearchModes: ["broad"],
    canSaveCampaigns: false,
    canUseExtension: true,
    canUseGoogleIntent: false,
    canUseGoogleOpenWeb: true,
    maxTeamMembers: 1,
  },
  growth: {
    label: "Growth",
    maxLeads: 2000,
    canImportCsv: true,
    canUseAiSearch: true,
    aiSearchModes: ["broad", "balanced"],
    canSaveCampaigns: true,
    canUseExtension: true,
    canUseGoogleIntent: true,
    canUseGoogleOpenWeb: true,
    maxTeamMembers: 3,
  },
  pro: {
    label: "Pro",
    maxLeads: 10000,
    canImportCsv: true,
    canUseAiSearch: true,
    aiSearchModes: ["broad", "balanced", "precise"],
    canSaveCampaigns: true,
    canUseExtension: true,
    canUseGoogleIntent: true,
    canUseGoogleOpenWeb: true,
    maxTeamMembers: 5,
  },
  scale: {
    label: "Scale",
    maxLeads: 50000,
    canImportCsv: true,
    canUseAiSearch: true,
    aiSearchModes: ["broad", "balanced", "precise"],
    canSaveCampaigns: true,
    canUseExtension: true,
    canUseGoogleIntent: true,
    canUseGoogleOpenWeb: true,
    maxTeamMembers: 15,
  },
};

export const DEFAULT_PLAN = "starter";